name: pay_for_cause
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  animated_text_kit: ^2.2.0
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.0+2
  firebase_storage: ^4.0.0
  firebase_database: ^4.0.0
  modal_progress_hud: ^0.1.3
  connectivity_wrapper: ^1.0.4
  loading_indicator: ^1.2.0
  loading: ^1.0.2
  provider: ^4.3.2+2
  cached_network_image_builder: ^0.1.0
  fluttertoast: ^7.1.1
  skeleton_text: ^1.0.0
  flutter_linkify: ^4.0.2
  font_awesome_flutter: ^8.11.0
  url_launcher: ^5.7.10
  razorpay_flutter: ^1.2.3
  toast: ^0.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
